Secure api
Ouckah/pipelines pull request #123
Opened 2024-03-28 23:08 UTC by Ouckah

ADDED SECURITY TO BACKEND!

2024-03-28 23:34 UTC, Nyumat requested changes
Can we abstract fetch calls to a reusable method, so we don't need to repeat ourselves with this:

``` Authorization: `Bearer ${Cookies.get('sessionId')}`,```

For every fetch call in the client code?

What I'd do is make a class or method that idiomatically takes in a session ID and anonymous request data, then makes the corresponding fetch request with the authorization headers attached. DRY, baby!

Everything else LGTM.

2024-03-28 23:35 UTC, Ouckah commented
> Can we abstract fetch calls to a reusable method, so we don't need to repeat ourselves with this:
> 
> `` Authorization: `Bearer ${Cookies.get('sessionId')}`, ``
> 
> For every fetch call in the client code?
> 
> What I'd do is make a class or method that idiomatically takes in a session ID and anonymous request data, then makes the corresponding fetch request with the authorization headers attached. DRY, baby!
> 
> Everything else LGTM.

That's what I was thinking, definitely felt repetitive, I'll do that RN

2024-03-28 23:45 UTC, Nyumat commented
This might add more code, but in the long run, I think we'll thank ourselves. Additionally, I'd look into [joi](https://www.npmjs.com/package/joi) for validating the schema (request body for each request)

2024-03-28 23:45 UTC, Nyumat commented
> > Can we abstract fetch calls to a reusable method, so we don't need to repeat ourselves with this:
> > `` Authorization: `Bearer ${Cookies.get('sessionId')}`, ``
> > For every fetch call in the client code?
> > What I'd do is make a class or method that idiomatically takes in a session ID and anonymous request data, then makes the corresponding fetch request with the authorization headers attached. DRY, baby!
> > Everything else LGTM.
> 
> That's what I was thinking, definitely felt repetitive, I'll do that RN

Yeah..in the long run, I think we'll thank ourselves. Additionally, I'd look into [joi](https://www.npmjs.com/package/joi) for validating the schema (request body for each request)

2024-03-29 00:27 UTC, slackroad requested changes

2024-03-29 00:27 UTC, slackroad commented on client/src/context/SessionContext.js
> +            console.log(currentSessionId)
remove

2024-03-29 00:27 UTC, slackroad commented on client/src/context/SessionContext.js
> +                        throw new Error('Network response was not ok')
what we want to do here is check if the session is expired. so if the token that we used before is too old, then we need to regenerate a token and send it here to be used.

2024-03-29 00:27 UTC, slackroad commented on server/middleware/token.js
> +    return res.status(400).json({ msg: "Invalid or expired token." });
if token is expired, need to generate a new one

2024-03-29 19:03 UTC, arfpog approved these changes

2024-03-29 20:00 UTC, Nyumat approved these changes
marvelous. ggs.

2024-03-29 20:01 UTC, merged