Add README
Ouckah/pipelines pull request #78
Opened 2024-01-24 11:33 UTC by Rakoski

Pls accept pull

2024-01-24 14:43 UTC, Lewin-B requested changes
I love it and thank you so much, Just left a few comments on some things but again thank you

2024-01-24 14:43 UTC, Lewin-B commented on README.md
> +5. **Add LinkedIn Experience**: Add new experience entries to LinkedIn profiles.
I'm not sure what this means but I would reword it so that its clear that our changes only effect our site

2024-01-24 14:43 UTC, Lewin-B commented on README.md
> +6. **Get Profiles**: Retrieve a list of LinkedIn profiles.
Same as my first comment

2024-01-24 14:43 UTC, Lewin-B commented on README.md
> +7. **Delete Profiles**: Remove LinkedIn profiles from the system.
Same as my first comment

2024-01-24 14:43 UTC, Lewin-B commented on README.md
> +8. **Update Profiles**: Modify existing LinkedIn profiles.
Same as my first comment

2024-01-24 14:43 UTC, Lewin-B commented on README.md
> +## Technologies Used
I would add Node.js to technologies used as well

2024-01-24 16:47 UTC, Lewin-B requested changes
One last thing

2024-01-24 16:47 UTC, Lewin-B commented on README.md
> +7. **Delete Profiles**: Remove user profiles and their LinkedIn profiles from the pipeilnes.lol.
I would get rid of the "The" so it either says "from pipelines.lol" or "from the pipelines.lol webpage" also pipelines is mispelled

2024-01-24 18:06 UTC, Lewin-B approved these changes
Looks Good to me!

2024-01-25 00:51 UTC, Rakoski commented
Thanks man! I still need another person to review it for it to actually enter the repo

2024-01-25 01:05 UTC, Ouckah commented
Hi Rako!

Unfortunately, we are in no need for a contribution for our README file. We appreciate the contribution but we will not be pulling your changes.

- Aidan

2024-01-25 01:06 UTC, closed without merging