Education Profile
Ouckah/pipelines pull request #82
Opened 2024-01-25 17:58 UTC by Ouckah

- Added implementation for user to add education / school
- Utilized an API from a GitHub repo: https://github.com/Hipo/university-domains-list
- Slightly changed the profile schema to include school
- Created a new search query for education

2024-01-25 17:59 UTC, Ouckah reviewed
omg this is so good aidan good job

2024-01-28 17:04 UTC, Lewin-B requested changes
Looks good outside some styling issues I left a few comments.

2024-01-28 17:04 UTC, Lewin-B commented on client/src/components/SchoolQuerySearch.js
> +                    className={`z-10 max-h-36 w-full -translate-y-4 overflow-y-scroll bg-white shadow-md ${hasResults ? 'absolute top-full' : ''}`}
The search results are on too low of a Z index it's going under the Experience Form component

2024-01-28 17:04 UTC, Lewin-B commented on client/src/components/SchoolQuerySearch.js
> +                        'z-20 w-full rounded-full bg-gray-100 px-4 py-2 text-gray-800 outline-none'
The color of the input is a little bright in my opinion

2024-01-28 17:04 UTC, Lewin-B commented on client/src/pages/Profile.js
> +                        <div className="flex h-full w-full flex-col items-center justify-center gap-5 bg-white p-10 shadow-md">
This whole section should be the same color as everything else on the page

2024-01-29 05:40 UTC, Lewin-B requested changes
You're failing all the checks run "npm run lint:fix".
Also the search results are still white and the z index is still off

2024-01-29 17:37 UTC, Lewin-B approved these changes
Great job on the changes Lewin. looks good to me

2024-01-29 17:37 UTC, merged